# Generated by Django 5.2.7 on 2025-11-01 17:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('image', models.ImageField(default='default_category.jpg', upload_to='category/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.company')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('source', models.CharField(choices=[('Bought', 'Bought'), ('Manufactured', 'Manufactured')], max_length=20)),
                ('buying_price', models.FloatField(blank=True, null=True)),
                ('manufacture_price', models.FloatField(blank=True, null=True)),
                ('selling_price', models.FloatField()),
                ('min_selling_price', models.FloatField(default=0)),
                ('sku', models.CharField(blank=True, help_text='Stock Keeping Unit (unique identifier)', max_length=100)),
                ('specifications', models.TextField(blank=True)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('image', models.ImageField(default='default_product.jpg', upload_to='product/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.category')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.company')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
