# Generated by Django 5.2.7 on 2025-11-26 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lead',
            old_name='notes',
            new_name='address',
        ),
    ]
