# Generated by Django 5.2.7 on 2025-11-26 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_rename_notes_lead_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='address',
            field=models.TextField(),
        ),
    ]
